### ISSUE TITLE
Definir git workflow

### ISSUE THREAD

**Issue by AyudantesTecnicas** [TP0602-07/grupo-07#1]
Elegir la forma en que van a utilizar el repositorio git. Definir los nombres de los branchs y la forma de trabajo.

**Comment by AyudantesTecnicas** [comment]
Una vez definido, documentarlo  en el readme del proyecto.

**Comment by Adbonino** [comment]
Hola Gente como estan?
Ai estuve mirando algo el tp, hoy a la noche lo miro poruqe estoy a full
con tecnicas.
Creo que ya casi esta, o prbaron ya?
si falta algo avisenme y le pongo fichas a la noche.

Saludos

2016-09-22 0:28 GMT-03:00 Pablo Ivancich notifications@github.com:
