### ISSUE TITLE
Completar ejercitacion de la entrega 1

### ISSUE THREAD

**Issue by AyudantesTecnicas** [TP0602-07/grupo-07#19]

**Comment by pabloivancich** [comment]
Relacionadas a esta tarea vamos a sacar varias tareas de refactor, reimplementacion y finalizacion de otras cosas. Por ejemplo los refactors de reglas y board

**Comment by pabloivancich** [comment]
De esta tarea vamos a sacar otras mas puntuales relacionada a la actividad del dia de la entrega. por ejemplo la relacionada a lectura de jugadas
