### ISSUE TITLE
Completar implementación de juegos

### ISSUE THREAD

**Issue by AyudantesTecnicas** [TP0602-07/grupo-07#52]
La segunda iteración, al inciar ofrece los juegos pero solamente se puede jugar al sudoku. 
El kakuro muestra cuadros blancos, el Country Road es una matriz con todos '1',  SlitherLink, Gogiken y Ishi No Heya indican que no tienen archivo de cnfiguración,

**Comment by pabloivancich** [comment]
Esto ya lo charlamos con Florencia. Vamos a crear tareas individuales por cada cosa que nos quede completar
